#!/usr/bin/env python3
"""Generate the Worker PSL module from the pinned OpenJDK PSL archive."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
import zipfile


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "vendor/public-suffix-list/openjdk-public_suffix_list.dat"
OUTPUT = ROOT / "src/v2/storage/public-suffix-list.generated.js"
SOURCE_SHA256 = "16b42002aa6f83a7763c4cdbd399ecf738460377d447e362884495545afd60a3"


def ascii_rule(rule: str) -> str:
    prefix = ""
    if rule[:1] in {"!", "*"}:
        prefix, rule = rule[0], rule[1:]
    labels = [label.encode("idna").decode("ascii") for label in rule.lstrip(".").split(".")]
    return prefix + ("." if prefix == "*" else "") + ".".join(labels)


def read_rules() -> tuple[list[str], list[str], list[str]]:
    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    if digest != SOURCE_SHA256:
        raise SystemExit(f"Pinned PSL checksum mismatch: expected {SOURCE_SHA256}, got {digest}")

    exact: set[str] = set()
    wildcard: set[str] = set()
    exception: set[str] = set()
    with zipfile.ZipFile(SOURCE) as archive:
        for member in sorted(archive.namelist()):
            for raw_line in archive.read(member).splitlines():
                if not raw_line:
                    continue
                section, raw_rule = raw_line[0], raw_line[1:]
                if section not in (0, 1):
                    raise SystemExit(f"Unknown PSL section marker {section} in {member}")
                rule = ascii_rule(raw_rule.decode("utf-8").strip().lower())
                if rule.startswith("!"):
                    exception.add(rule[1:])
                elif rule.startswith("*."):
                    wildcard.add(rule[2:])
                else:
                    exact.add(rule)
    return sorted(exact), sorted(wildcard), sorted(exception)


def render() -> str:
    exact, wildcard, exception = read_rules()
    payload = (
        "// Generated by scripts/generate-public-suffix-list.py; do not edit.\n"
        f"// Source SHA-256: {SOURCE_SHA256}\n"
        "// Includes both ICANN and PRIVATE sections.\n"
        f"export const PUBLIC_SUFFIX_EXACT_RULES = {json.dumps(exact, ensure_ascii=True, separators=(',', ':'))};\n"
        f"export const PUBLIC_SUFFIX_WILDCARD_RULES = {json.dumps(wildcard, ensure_ascii=True, separators=(',', ':'))};\n"
        f"export const PUBLIC_SUFFIX_EXCEPTION_RULES = {json.dumps(exception, ensure_ascii=True, separators=(',', ':'))};\n"
    )
    return payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
